#!/bin/bash

log_each_line() {
while read line
do
	/usr/bin/logger --journald <<-EOM
		SYSLOG_IDENTIFIER=environment-manager
		MESSAGE=$line
	EOM
done
}


/usr/bin/node index.js mode=Release 2>&1 | log_each_line
